CREATE TABLE "ADMIN"
(	"ADMIN_ID" VARCHAR2(100) NOT NULL ENABLE,
     "ADMIN_NAME" VARCHAR2(100),
     "ADMIN_ROLE" VARCHAR2(20),
     CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ADMIN_ID")
);

CREATE TABLE "API_INFO"
(	"URI" VARCHAR2(1000) NOT NULL ENABLE,
     "PARAMS" VARCHAR2(1000),
     "CLIENT_IP" VARCHAR2(15) NOT NULL ENABLE,
     "ACCESS_TOKEN" VARCHAR2(100),
     "HTTP_METHOD" VARCHAR2(6) NOT NULL ENABLE,
     "HEADERS" VARCHAR2(100),
     "SECRET_KEY" VARCHAR2(200),
     "TOKEN_NUM" NUMBER(6,0),
     CONSTRAINT "API_INFO_PK" PRIMARY KEY ("URI")
);

CREATE TABLE "REFRESH_TOKEN"
(	"TOKEN_NUM" NUMBER(6,0) NOT NULL ENABLE,
     "URI" VARCHAR2(1000) NOT NULL ENABLE,
     "TOKEN" VARCHAR2(300) NOT NULL ENABLE,
     "EXPRIYR_DATE" DATE,
     CONSTRAINT "REFRESH_TOKEN_PK" PRIMARY KEY ("TOKEN_NUM")
);

CREATE TABLE "ROLE_INFO"
(	"ROLE_NUM" NUMBER(6,0) NOT NULL ENABLE,
     "PERMISSION_DATA" VARCHAR2(100),
     "ROLE" VARCHAR2(100) NOT NULL ENABLE,
     CONSTRAINT "ROLE_INFO_PK" PRIMARY KEY ("ROLE_NUM")
);

ALTER TABLE "API_INFO" ADD CONSTRAINT "API_INFO_REFRESH_TOKEN_FK" FOREIGN KEY ("TOKEN_NUM")
    REFERENCES "REFRESH_TOKEN" ("TOKEN_NUM") ON DELETE CASCADE ENABLE;

ALTER TABLE "REFRESH_TOKEN" ADD CONSTRAINT "REFRESH_TOKEN_API_INFO_FK" FOREIGN KEY ("URI")
    REFERENCES "API_INFO" ("URI") ON DELETE CASCADE ENABLE;


